"""Runtime environment service: requirements manifest, image builds and cluster validations.

Model: libraries + job code are baked into a versioned Docker image (never `pip install` on live
pods). The worker runs `docker build` against the host daemon (dev) — in K8s this is a CI step.
Cluster validation runs the system Spark jobs distributed across the workers (via `docker exec`
into a Spark container so the driver Python matches the executors).
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
import urllib.request
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from t2c_ingest.core.config import settings
from t2c_ingest.models.runtime import RuntimeBuild, RuntimeLibrary, RuntimeValidation

# Files that must never be copied into an image.
_SECRET_NAMES = {".env", ".pem", ".key", ".crt", ".p12", ".jks"}
_SECRET_EXTS = {".env", ".pem", ".key", ".crt", ".p12", ".jks"}

DOCKERFILE_TEMPLATE = """\
# Generated by T2C Data Ingest — cluster runtime image (libraries + jobs baked in).
FROM {base_image}

USER root

COPY runtime/requirements.txt /opt/t2c/requirements/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /opt/t2c/requirements/requirements.txt

COPY spark/jobs /opt/t2c/spark/jobs
COPY python_jobs /opt/t2c/python_jobs
COPY spark/jars /opt/spark/jars

ENV PYTHONPATH=/opt/t2c:/opt/t2c/spark/jobs:/opt/t2c/python_jobs
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

WORKDIR /opt/t2c
USER 185
"""


def _now() -> datetime:
    return datetime.now(timezone.utc)


def generate_requirements(db: Session) -> str:
    """Render requirements.txt from the ACTIVE runtime libraries (sorted, deterministic)."""
    libs = db.scalars(
        select(RuntimeLibrary).where(RuntimeLibrary.active.is_(True)).order_by(RuntimeLibrary.package_name)
    ).all()
    lines = [lib.package_spec for lib in libs]
    header = "# Gerado automaticamente pelo T2C Data Ingest a partir das bibliotecas ativas do runtime.\n"
    return header + "\n".join(lines) + ("\n" if lines else "")


def _ignore_secrets(_dir: str, names: list[str]) -> set[str]:
    ignored = set()
    for name in names:
        lower = name.lower()
        if lower in _SECRET_NAMES or os.path.splitext(lower)[1] in _SECRET_EXTS or name == "__pycache__":
            ignored.add(name)
    return ignored


def _copytree(src: str, dst: str) -> None:
    if os.path.isdir(src):
        shutil.copytree(src, dst, dirs_exist_ok=True, ignore=_ignore_secrets)
    else:
        os.makedirs(dst, exist_ok=True)


def _docker_available() -> bool:
    return shutil.which("docker") is not None


# ── build ──
def run_build(db: Session, build: RuntimeBuild) -> None:
    """Assemble the build context (Dockerfile + requirements + jobs) and run `docker build`."""
    build.status = "building"
    build.started_at = _now()
    db.commit()
    _audit(db, "RUNTIME_BUILD_STARTED", build)

    ctx = os.path.join(settings.runtime_build_context_dir, build.build_version)
    logs: list[str] = []
    ok = False
    error = None
    try:
        # 1) Assemble context (inside the worker; the docker CLI streams it to the daemon).
        os.makedirs(os.path.join(ctx, "runtime"), exist_ok=True)
        with open(os.path.join(ctx, "runtime", "requirements.txt"), "w", encoding="utf-8") as fh:
            fh.write(build.requirements_snapshot or "")
        with open(os.path.join(ctx, "Dockerfile"), "w", encoding="utf-8") as fh:
            fh.write(DOCKERFILE_TEMPLATE.format(base_image=settings.runtime_base_image))
        with open(os.path.join(ctx, ".dockerignore"), "w", encoding="utf-8") as fh:
            fh.write("**/.env\n**/*.pem\n**/*.key\n**/*.crt\n**/__pycache__\n")
        _copytree("/opt/t2c/spark/jobs", os.path.join(ctx, "spark", "jobs"))
        _copytree("/opt/t2c/python_jobs", os.path.join(ctx, "python_jobs"))
        _copytree("/app/jars", os.path.join(ctx, "spark", "jars"))
        snapshot = _jobs_snapshot(ctx)
        with open(os.path.join(ctx, "jobs_snapshot.json"), "w", encoding="utf-8") as fh:
            json.dump(snapshot, fh, ensure_ascii=False, indent=2)

        build.context_path = ctx
        build.dockerfile_path = os.path.join(ctx, "Dockerfile")
        build.jobs_snapshot_path = os.path.join(ctx, "jobs_snapshot.json")
        logs.append(f"Contexto gerado em {ctx} ({snapshot['file_count']} arquivos de código).")
        db.commit()

        # 2) docker build.
        if not _docker_available():
            raise RuntimeError(
                "Docker CLI indisponível no worker. Contexto gerado; execute o build no host/CI: "
                f"docker build -t {build.image_full_name} {ctx}"
            )
        cmd = ["docker", "build", "-t", build.image_full_name, ctx]
        logs.append(f"$ {' '.join(cmd)}")
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=settings.runtime_build_timeout)
        logs.append(proc.stdout)
        if proc.stderr:
            logs.append(proc.stderr)
        ok = proc.returncode == 0
        if not ok:
            error = (proc.stderr or proc.stdout or "docker build falhou").strip()[:2000]
    except subprocess.TimeoutExpired:
        error = f"Tempo limite de build ({settings.runtime_build_timeout}s) excedido."
        logs.append(error)
    except Exception as exc:  # noqa: BLE001
        error = str(exc)
        logs.append(f"[erro] {error}")

    build.finished_at = _now()
    build.duration_seconds = int((build.finished_at - build.started_at).total_seconds())
    build.status = "success" if ok else "failed"
    build.build_logs = "\n".join(p for p in logs if p)[:200_000]
    build.error_message = error
    db.commit()
    _audit(db, "RUNTIME_BUILD_SUCCEEDED" if ok else "RUNTIME_BUILD_FAILED", build)


def _jobs_snapshot(ctx: str) -> dict:
    files = []
    for base in ("spark/jobs", "python_jobs"):
        root = os.path.join(ctx, base)
        for dirpath, _dirs, names in os.walk(root):
            for n in names:
                rel = os.path.relpath(os.path.join(dirpath, n), ctx)
                files.append(rel)
    return {"file_count": len(files), "files": sorted(files)}


def _docker(args: list[str], timeout: int = 120) -> subprocess.CompletedProcess:
    return subprocess.run(["docker", *args], capture_output=True, text=True, timeout=timeout)


def _recreate_worker(name: str, image: str) -> str:
    """Recreate a compose worker container with a new image, cloning its config via inspect.

    Bind mounts / networks / ports / command come from `docker inspect` so host-absolute paths
    stay correct (only the host daemon can honor them). Runs from the worker via the mounted
    socket. Returns a human-readable log line.
    """
    insp = _docker(["inspect", name])
    if insp.returncode != 0:
        return f"  {name}: inspeção falhou ({insp.stderr.strip()[:120]})"
    data = json.loads(insp.stdout)[0]
    cfg, host, nets = data["Config"], data["HostConfig"], data["NetworkSettings"]["Networks"]
    hostname = cfg.get("Hostname") or name
    cmd = cfg.get("Cmd") or []
    binds = host.get("Binds") or []
    net_name = next(iter(nets), None)
    aliases = [a for a in (nets.get(net_name, {}).get("Aliases") or []) if a and a != data.get("Id", "")[:12]]
    ports = host.get("PortBindings") or {}
    # Preserve docker-compose labels so Compose keeps managing the container after recreate.
    labels = {k: v for k, v in (cfg.get("Labels") or {}).items() if k.startswith("com.docker.compose")}

    run = ["run", "-d", "--name", name, "--hostname", hostname, "--restart", "no"]
    for k, v in labels.items():
        run += ["--label", f"{k}={v}"]
    if net_name:
        run += ["--network", net_name]
        for alias in aliases:
            run += ["--network-alias", alias]
    for b in binds:
        run += ["-v", b]
    for cport, maps in ports.items():
        for m in maps:
            hostport = m.get("HostPort")
            if hostport:
                run += ["-p", f"{hostport}:{cport.split('/')[0]}"]
    run += [image, *cmd]

    rm = _docker(["rm", "-f", name])
    created = _docker(run)
    if created.returncode != 0:
        return f"  {name}: recriação falhou ({created.stderr.strip()[:160]})"
    return f"  {name}: recriado com {image} (rm={'ok' if rm.returncode == 0 else 'skip'})"


def _wait_for_workers(expected: int, timeout: int = 60) -> tuple[int, str]:
    """Poll the Spark master REST until >= expected workers are ALIVE (or timeout)."""
    url = settings.runtime_spark_master_webui.rstrip("/") + "/json/"
    deadline = time.monotonic() + timeout
    detected = 0
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=5) as resp:
                payload = json.loads(resp.read().decode())
            detected = len([w for w in payload.get("workers", []) if w.get("state") == "ALIVE"])
            if detected >= expected:
                return detected, f"Workers ALIVE: {detected}/{expected}"
        except Exception:  # noqa: BLE001
            pass
        time.sleep(3)
    return detected, f"Workers ALIVE após timeout: {detected}/{expected}"


def apply_active_image(db: Session) -> tuple[bool, str, RuntimeBuild | None]:
    """Retag the active build image to the workers' tag and recreate the local worker containers."""
    build = db.scalar(select(RuntimeBuild).where(RuntimeBuild.is_active.is_(True)).limit(1))
    if build is None:
        return False, "Nenhuma imagem runtime ativa. Ative um build antes de aplicar.", None
    if not _docker_available():
        return False, "Docker CLI indisponível no worker.", build

    logs = [f"Aplicando imagem ativa {build.image_full_name} aos workers do cluster."]
    tag = _docker(["tag", build.image_full_name, settings.runtime_worker_image_tag])
    if tag.returncode != 0:
        return False, f"Falha ao retaggear imagem: {tag.stderr.strip()[:160]}", build
    logs.append(f"docker tag {build.image_full_name} {settings.runtime_worker_image_tag}")

    for name in settings.runtime_spark_worker_containers_list:
        logs.append(_recreate_worker(name, settings.runtime_worker_image_tag))
    detected, wait_msg = _wait_for_workers(settings.spark_expected_workers)
    logs.append(wait_msg)
    ok = detected >= settings.spark_expected_workers
    return ok, "\n".join(logs), build


def activate_build(db: Session, build: RuntimeBuild) -> None:
    db.query(RuntimeBuild).filter(RuntimeBuild.id != build.id, RuntimeBuild.is_active.is_(True)).update(
        {"is_active": False, "status": "deprecated"}
    )
    build.is_active = True
    build.status = "active"
    db.commit()
    _audit(db, "RUNTIME_BUILD_ACTIVATED", build)


# ── validation ──
def run_validation(db: Session, validation: RuntimeValidation) -> None:
    """Run a distributed validation Spark job across the workers and parse its JSON result."""
    validation.status = "running"
    validation.started_at = _now()
    db.commit()
    _audit(db, "RUNTIME_VALIDATION_STARTED", validation)

    expected = validation.worker_count_expected or settings.spark_expected_workers
    apply_log = ""
    apply_failed = False
    if validation.validation_type == "apply":
        # Deploy the active image to the workers, then validate libraries on the new cluster.
        ok, apply_log, _build = apply_active_image(db)
        apply_log += "\n"
        apply_failed = not ok
        validation.validation_type = "libraries"  # the result IS a libraries validation
        if not validation.libraries_checked:
            validation.libraries_checked = [
                lib.package_name for lib in db.scalars(
                    select(RuntimeLibrary).where(RuntimeLibrary.active.is_(True))
                ).all()
            ]

    if validation.validation_type == "libraries":
        libs = ",".join(validation.libraries_checked or []) if isinstance(validation.libraries_checked, list) else ""
        script = "/opt/t2c/spark/jobs/system/validate_runtime_libraries.py"
        extra = ["--libs", libs, "--expected-workers", str(expected)]
    else:
        script = "/opt/t2c/spark/jobs/system/validate_distributed_execution.py"
        extra = ["--partitions", str(max(30, expected * 6)), "--expected-workers", str(expected)]

    logs = ""
    parsed = None
    error = None
    try:
        if apply_failed:
            raise RuntimeError("Falha ao aplicar a imagem ativa aos workers (veja os logs).")
        logs, parsed = _spark_submit_validation(script, extra)
        if parsed is None:
            error = "Não foi possível interpretar o resultado da validação (RUNTIME_VALIDATION_JSON ausente)."
    except Exception as exc:  # noqa: BLE001
        error = str(exc)
        logs = logs or f"[erro] {error}"

    validation.finished_at = _now()
    validation.logs = ((apply_log + (logs or "")) or "")[:200_000]
    if parsed:
        validation.worker_count_detected = parsed.get("detected_workers")
        validation.workers_result = parsed.get("by_host")
        if validation.validation_type == "libraries":
            validation.workers_result = {"by_host": parsed.get("by_host"), "failures": parsed.get("failures")}
        validation.status = "success" if parsed.get("status") == "success" else "failed"
        if validation.status == "failed" and not error:
            error = "Validação falhou — verifique os logs (workers insuficientes ou biblioteca ausente)."
    else:
        validation.status = "failed"
    validation.error_message = error
    db.commit()
    _audit(db, "RUNTIME_VALIDATION_SUCCEEDED" if validation.status == "success" else "RUNTIME_VALIDATION_FAILED", validation)


def _spark_submit_validation(script: str, extra: list[str]) -> tuple[str, dict | None]:
    """Run spark-submit for a validation job (driver in a Spark container to match executor Python)."""
    container = settings.runtime_spark_submit_container
    if container and _docker_available():
        # Driver runs INSIDE a Spark container (via docker exec) so its Python matches the
        # executors (both the runtime image). Uses the container's own hostname as driver host.
        submit = (
            "/opt/spark/bin/spark-submit"
            f" --master {settings.spark_master_url}"
            " --conf spark.driver.host=$(hostname)"
            " --conf spark.executor.cores=1"
            f" {script} {' '.join(extra)}"
        )
        cmd = ["docker", "exec", container, "bash", "-lc", submit]
    else:
        # Fallback: submit from the worker (works for non-Python-UDF jobs / matching Python).
        cmd = ["/opt/spark/bin/spark-submit", "--master", settings.spark_master_url,
               "--conf", "spark.executor.cores=1", script, *extra]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=settings.runtime_build_timeout)
    out = f"$ {' '.join(cmd)}\n\n{proc.stdout}\n{proc.stderr}"
    parsed = None
    for line in (proc.stdout + "\n" + proc.stderr).splitlines():
        idx = line.find("RUNTIME_VALIDATION_JSON:")
        if idx != -1:
            try:
                parsed = json.loads(line[idx + len("RUNTIME_VALIDATION_JSON:"):].strip())
            except json.JSONDecodeError:
                parsed = None
    return out, parsed


def _audit(db: Session, event: str, entity) -> None:
    from t2c_ingest.models.audit import AuditEvent

    try:
        db.add(AuditEvent(
            action=event, entity_type="runtime",
            entity_id=str(getattr(entity, "id", "")),
            user_email=getattr(entity, "created_by", None),
            detail={"event": event},
        ))
        db.flush()
        db.commit()
    except Exception:  # noqa: BLE001
        db.rollback()
